name: sqfentity_example
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework. 
author: Hüseyin TOKPINAR <hhtokpinar@gmail.com>
homepage: https://github.com/hhtokpinar/sqfEntity


version: 1.3.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7
  http: ^0.12.0+1 
  flutter_datetime_picker:
    git:
      url: https://github.com/derohimat/flutter_datetime_picker.git  
  sqfentity: 
  sqfentity_gen: 
  
dependency_overrides:
  sqfentity: 
    path: ../sqfentity
  sqfentity_gen: 
    path: ../sqfentity_gen      

    
 
dev_dependencies:
  build_runner: ^1.6.5
  build_verify: ^1.1.0
  sqflite_common_ffi:
  
  
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/chinook.sqlite
    - line.png
    - windows-wallpaper.jpg
    - no-picture.png
  
  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
          style: normal
    
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Thin.ttf
          style: normal
              
